DROP SEQUENCE expositor_seq;
DROP SEQUENCE evento_seq;
DROP SEQUENCE endereco_seq;
DROP SEQUENCE categoria_seq;
DROP SEQUENCE local_seq;
DROP SEQUENCE status_seq;
DROP SEQUENCE municipio_seq;
DROP SEQUENCE uf_seq;
DROP SEQUENCE telefone_seq;
DROP SEQUENCE email_seq;
DROP SEQUENCE expositorevento_seq;
DROP SEQUENCE expositorcategoria_seq;

DROP TABLE Expositor CASCADE CONSTRAINTS;
DROP TABLE Evento CASCADE CONSTRAINTS;
DROP TABLE Endereco CASCADE CONSTRAINTS;
DROP TABLE Categoria CASCADE CONSTRAINTS;
DROP TABLE Local CASCADE CONSTRAINTS;
DROP TABLE Status CASCADE CONSTRAINTS;
DROP TABLE Municipio CASCADE CONSTRAINTS;
DROP TABLE UF CASCADE CONSTRAINTS;
DROP TABLE Telefone CASCADE CONSTRAINTS;
DROP TABLE Email CASCADE CONSTRAINTS;
DROP TABLE ExpositorEvento CASCADE CONSTRAINTS;
DROP TABLE ExpositorCategoria CASCADE CONSTRAINTS;

